services:
  prometheus:
    image: quay.io/prometheus/prometheus:v3.4.2
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prom_data:/prometheus
    environment:
      - PROMETHEUS_USERNAME=${PROMETHEUS_USERNAME}
      - PROMETHEUS_PASSWORD=${PROMETHEUS_PASSWORD}
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

volumes:
  prom_data:
    driver: local