global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "homelab"
    static_configs:
      - targets: ["node-exporter.dropbear-butterfly.ts.net"]
        labels:
          app: "homelab"
