global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "homelab"
    static_configs:
      - targets: ["100.70.115.42:9100"]
        labels:
          app: "homelab"

remote_write:
  - url: https://openobserve.dropbear-butterfly.ts.net/api/default/prometheus/api/v1/write
    queue_config:
      max_samples_per_send: 10000
    basic_auth:
      username: ${PROMETHEUS_USERNAME}
      password: ${PROMETHEUS_PASSWORD}
